### ISSUE TITLE
Add SmartCash (SMART)

### ISSUE THREAD

**Issue by blockchainlibraryorg** [guardaco/crypto-icons#3]
Currency name: SmartCash
Symbol: SMART
Website: https://smartcash.cc/
Theme color: #FEC60D
Logo (SVG): [SVG Logo SmartCash.zip](https://github.com/guardaco/crypto-icons/files/2325651/SVG.Logo.SmartCash.zip)

**Comment by dintores** [comment]
@blockchainlibraryorg Hey!
I added this icon 😀

**Comment by blockchainlibraryorg** [comment]
Thanks!
